### PR TITLE
bumped Django version to include 1.11

### PR DESCRIPTION
**Pull request by soby**

### CODE REVIEW

**Comment by soby** [comment]
django-closuretree seems to work find for Django 1.11 so I bumped the allowed versions to include it. 

It looks like the Travis failure is a function of https://github.com/mikebryant/django-autoconfig not supporting Django 1.11. 

@mikebryant It looks like this is also you're lib. Any plans on Django 1.11 support for it? If not, is it a key dependency for django-closuretree?

**Comment by mikebryant** [comment]
@soby Yeh, I'd like to support it. I'm hoping to do this on the weekend :)

**Comment by soby** [comment]
@mikebryant any luck with django-autoconfig?

**Comment by mikebryant** [comment]
Thanks for this, sorry, I've not been on the ball here.
Will get this in today

**Comment by mikebryant** [comment]
@soby Really sorry this took so long.

**Comment by soby** [comment]
All good, completely understand

**Pull request closed without merging**
